Fix cosmic HI fraction plot
SWIFTSIM/pipeline-configs pull request #163
Opened 2022-03-14 11:43 UTC by MatthieuSchaller

Three changes:
 - Remove Walter et al. 2020 data
 - Correct the simulations for He abundance
 - Add cosmology correction from Schaye+01

2022-03-15 11:03 UTC, EvgeniiChaikin commented on colibre/scripts/HI_mass_evolution.py
> +P20_rhoHI_hi /= 0.7 ** -1 * sqrt(0.3 * (1.0 + zgrid) ** 3 + 0.7)
I was running this branch and found a couple of typos. Below is a suggested change to resolve the typos.

```suggestion
P20_rhoHI *= cosmo.h ** -1 * np.sqrt(cosmo.Om0 * (1.0 + zgrid) ** 3 + cosmo.Ode0)
P20_rhoHI /= 0.7 ** -1 * np.sqrt(0.3 * (1.0 + zgrid) ** 3 + 0.7)
P20_rhoHI_lo *= cosmo.h ** -1 * np.sqrt(cosmo.Om0 * (1.0 + zgrid) ** 3 + cosmo.Ode0)
P20_rhoHI_lo /= 0.7 ** -1 * np.sqrt(0.3 * (1.0 + zgrid) ** 3 + 0.7)
P20_rhoHI_hi *= cosmo.h ** -1 * np.sqrt(cosmo.Om0 * (1.0 + zgrid) ** 3 + cosmo.Ode0)
P20_rhoHI_hi /= 0.7 ** -1 * np.sqrt(0.3 * (1.0 + zgrid) ** 3 + 0.7)
```

2022-03-18 14:02 UTC, bwvdnbro requested changes
I think the helium correction that is mentioned in the caption and the script is a bit misleading; I had to read through Peroux & Howk (2020) to understand what is happening.
The fit in Peroux & Howk (2020) was made to the _neutral gas density_, which assumes a gas that consists of hydrogen and helium. However, this plot claims to show the _HI mass density_, so not including helium. Either the plot quantity needs to be renamed in the name of the plot and the labels, or the helium correction should be performed on the data and not on the simulation. Either way, it should not be called a _correction_; it is a _conversion factor_ because of a change of quantity.

2022-04-13 12:24 UTC, MatthieuSchaller commented on colibre/scripts/HI_mass_evolution.py
> +    HI_mass_density *= 1.0 / 0.76  # Apply Helium correction
Just saw I never replied. 

Agreed, my comment is not good enough. I am happy with either of your propositions. Feel free to make the changes in a way that makes everything clear for you also to maintain in the long run.

2022-04-13 15:26 UTC, bwvdnbro commented
Do we want to keep the commented out sections in the script?

2022-04-13 15:27 UTC, bwvdnbro approved these changes

2022-04-13 15:49 UTC, MatthieuSchaller commented
We could if we want to have that other dataset reappear in the future.

2022-04-14 07:13 UTC, bwvdnbro commented
What would be needed to make that dataset reappear? I'm happy to keep it like this, but it would be useful to provide a comment explaining why it was disabled and what would be needed to make it reappear.

2022-04-14 07:22 UTC, MatthieuSchaller commented
We are now correcting the simulation to match the Peroux dataset. 

The Walter dataset could reappear if the same correction (He) was applied.

2022-04-21 07:43 UTC, MatthieuSchaller commented
@jtrayford, I think you added the Walter data for the cosmic HI. Do you know whether they applied any He correction? Or any other correction?

2022-04-22 07:33 UTC, bwvdnbro commented
From the paper, section 3.2.2:
> However, we do account for the contribution of helium, which corresponds to a correction factor of μ = 1.3.

So the same correction as for the Peroux & Howk data.

2022-04-22 07:39 UTC, bwvdnbro commented
Do we also need the cosmology correction that was applied to the Peroux & Howk data? And where does this come from (Schaye 2001 is not a particularly clear reference - there are 4 of those)?

2022-04-22 07:43 UTC, MatthieuSchaller commented
It's eq. 14-15 of https://ui.adsabs.harvard.edu/abs/2001ApJ...559..507S/abstract

Yes, it would need to be applied as well. On top of the changes to rho_crit.

2022-04-22 08:45 UTC, bwvdnbro commented
I think everything is ready now. The plot now looks like this (the simulation is a 6 Mpc low resolution box):
![HI_mass_evolution](https://user-images.githubusercontent.com/7336967/164652592-90142989-30cd-438e-878c-43d3362d43a4.png)

2022-04-22 11:29 UTC, MatthieuSchaller commented
Thanks!

2022-04-22 11:29 UTC, MatthieuSchaller commented
Approved.

2022-04-28 11:22 UTC, merged