WIP: Update the SNIa plots to include the observations
SWIFTSIM/pipeline-configs pull request #223
Opened 2022-10-20 15:10 UTC by Fonotec

These are the current update to the plots of the SNIa rates.

2022-10-23 17:02 UTC, MatthieuSchaller commented
Assigned to Bert as he is already looking at the data side.

2022-10-26 08:40 UTC, bwvdnbro requested changes
I have added a comment to the registration functions. This issue recently popped up when using the SOAP rather than VR halo catalogue, since the units for the SFR are different there. Apparently `unyt` just ignores the units in comparisons, so if you use the wrong units, you get the wrong mask. I realise that some other registration functions are probably also wrong in that sense, but those can be fixed when we actually switch to using SOAP (that is still the plan).

I imagine that Joop will want more extensive captions for the new figures, but that can be done later too.

The link to the observational data repository still needs to be updated, but that can only be done after the changes there have been merged.

2022-10-26 08:40 UTC, bwvdnbro commented on colibre/registration.py
> +                (stellar_mass > unyt.unyt_quantity(1e10, units="Msun"))
Some recent experiences have taught us that you cannot rely on `unyt` doing the right thing when comparing `unyt_array`s; it tends to just completely ignore units. I therefore propose the following:
```
stellar_mass > (1.e10*unyt.Msun).to(stellar_mass.units)
...
ssfr > (1.01*marginal_ssfr).to(ssfr.units)
```

2022-10-26 08:40 UTC, bwvdnbro commented on colibre/registration.py
> +                (stellar_mass > unyt.unyt_quantity(5e10, units="Msun"))
Same here.

2022-10-26 08:40 UTC, bwvdnbro commented on colibre/registration.py
> +            (stellar_mass > unyt.unyt_quantity(5e10, units="Msun")).astype(float),
Same here.

2022-10-26 13:02 UTC, Fonotec commented
This is with your suggestions, btw we talked about this earlier, the Wiseman data will not appear on the plots this way. It has an average of z=0.5 but I would like to have it on the plot by default without needing to change the redshift of the data myself. The data for these SNIa surveys also do not work like other galaxy observations because it spans a more extended range in redshifts.

2022-10-28 14:07 UTC, bwvdnbro approved these changes

2022-11-01 09:07 UTC, Fonotec commented
Okay, I tried to update the observational_data folder, let me know if I did this correct

2022-11-01 14:28 UTC, bwvdnbro commented
No, something must have gone wrong, because there is a conflict. I will create a new branch based on your changes and merge it manually.

2022-11-01 14:45 UTC, bwvdnbro commented
I have made the changes in #226. Turns out you need to make sure the branch is up to date with master before updating the submodule (I think the submodule version changed in master as well, hence the conflict).

2022-11-01 14:49 UTC, closed without merging