Median temperature vs density plot (with metallicity bins)
SWIFTSIM/pipeline-configs pull request #234
Opened 2022-12-07 16:42 UTC by bwvdnbro

This PR adds a plot of the median temperature as a function of density, for all gas and for gas in selected metallicity bins.

The plot looks like this:
![median_temperature_density](https://user-images.githubusercontent.com/7336967/206238065-ddabf2ee-1e30-4a7c-b05a-3ea8af74b611.png)

Same, but for 2 and 3 snapshots being plotted:
![median_temperature_density](https://user-images.githubusercontent.com/7336967/206238201-4d8e9bed-bc65-46c1-9a06-362d290dd012.png)
![median_temperature_density](https://user-images.githubusercontent.com/7336967/206238260-d709191a-d656-4379-8913-9a4be0d9d05d.png)

As you can see, the legend is distributed over the panels if there are multiple plots, and is moved to the white area if that exists.

2022-12-12 16:15 UTC, EvgeniiChaikin requested changes
Thank you @bwvdnbro!

I left a few small suggestions in the script.

I also tested your script for a 5-run comparison. It looks good!
![median_temperature_density](https://user-images.githubusercontent.com/20153933/207096319-03273463-f31f-4f7b-87cf-13ddd4f34576.png)

One thing I do not understand is why the blue curve (all gas) does not converge to the orange curve (high-Z gas) at high densities when the other curves (lower-Z gas) are not present indicating that there is only high-Z gas. I would naively expect the blue to be very close to the orange in this case.

2022-12-14 15:03 UTC, bwvdnbro commented
The different metallicity bins do not completely span the entire possible range of metallicity values, so maybe that is why it does not converge?

And of course, there is also the issue that lines only show up if you have at least two adjacent bins that are not NaN. So maybe the high density bins are too sparsely populated when the metallicity cuts are applied?

2022-12-17 17:23 UTC, EvgeniiChaikin approved these changes
@bwvdnbro I found the reasons why the curves would not converge. That's because the temperature of all gas was computed as `median`, whereas the temperature in a given metallicity range was computed as `mean`.

If you replace `mean` with `median` by accepting my suggestion below, you will get the following plot
![median_temperature_density](https://user-images.githubusercontent.com/20153933/208253786-fa9ab182-4ef8-4a89-a317-9a3472bfaaa7.png)

which shows that two curves converge to the same values both at low Z and at high Z, as expected.

Apart from the above comment, this PR looks ready to be merged, so I will approve it in advance.

2022-12-17 17:23 UTC, EvgeniiChaikin commented on colibre/scripts/median_temperature_density.py
> +                        nH[mask], T[mask], statistic="mean", bins=nHbin
```suggestion
                        nH[mask], T[mask], statistic="median", bins=nHbin
```

2022-12-19 09:44 UTC, bwvdnbro commented on colibre/scripts/median_temperature_density.py
> +                        nH[mask], T[mask], statistic="mean", bins=nHbin
Oops, thanks for spotting that!

2022-12-19 09:45 UTC, merged