add neutral gas data comparison plots for individual galaxies
SWIFTSIM/pipeline-configs pull request #97
Opened 2021-02-23 16:43 UTC by wmfw23

2021-02-28 21:22 UTC, EvgeniiChaikin requested changes
Hi @wmfw23 I guess this PR goes together with your most recent PR to the comparison-data repository? 

If so, I suggest

1.  we first update the observational data repo to include your new files;
2.  and then proceed with this PR.

After step one is done, It would also be great if you could attach the observational-data submodule to the most recent commit so that it includes your new data.

2021-02-28 21:22 UTC, EvgeniiChaikin commented on colibre/auto_plotter/cold_gas_fractions.yml
> +    caption: Galaxy H_$2$ mass (including Helium following the observations) over stellar mass as a function of stellar mass in 0.2 dex bins, measured in 100 kpc apertures
Galaxy H_$2$  -> Galaxy H$_2$?

Also, it looks like the bins here are not 0.2 dex

2021-02-28 21:22 UTC, EvgeniiChaikin commented on colibre/auto_plotter/cold_gas_fractions.yml
> +    caption: Galaxy H_$2$ mass (including Helium following the observations) over neutral gas mass (HI+H$_2$) as a function of specific star formation rate in 0.2 dex bins, measured in 100 kpc apertu
-- Galaxy H_$2$ -> Galaxy H$_2$?
-- The comment says the bins here are 0.2 dex-wide but I don't think that is the case

2021-02-28 21:22 UTC, EvgeniiChaikin commented on colibre/auto_plotter/cold_gas_fractions.yml
> +    caption: Galaxy H_$2$ mass (including Helium following the observations) over stellar mass as a function of stellar mass in 0.2 dex bins, measured in 100 kpc apertures
You are plotting H2-to-neutral H fraction but the caption says H2 over stellar mass

2021-02-28 21:22 UTC, EvgeniiChaikin commented on colibre/auto_plotter/cold_gas_fractions.yml
> +    caption: Galaxy H_$2$ mass (including Helium following the observations) over stellar mass as a function of specific star formation rate in 0.2 dex bins, measured in 100 kpc apertures
Same comment about H_$2$ and bin size

2021-03-02 10:28 UTC, wmfw23 commented
Thanks Evgenii, yes once [This PR](https://github.com/SWIFTSIM/velociraptor-comparison-data/pull/75) is integrated into the main branch, I can update the submodule here to the main branch and push a commit

2021-03-15 12:56 UTC, EvgeniiChaikin commented on colibre/auto_plotter/cold_gas_fractions.yml
> +    number_of_bins: 30
@wmfw23 Can you change it to 25 and update the submodule, and then we merge it?

2021-03-18 14:56 UTC, EvgeniiChaikin approved these changes

2021-03-18 14:58 UTC, JBorrow commented
Please rebase before merging

2021-03-22 09:03 UTC, merged

2021-03-22 09:03 UTC, JBorrow commented
Thanks both for your help!